//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridPromocional.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridPromocional.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser mayor o igual a {1} y menor o igual a {2}.
        /// </summary>
        public static string ErrorRangeMaxMin {
            get {
                return ResourceManager.GetString("ErrorRangeMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser mayor o igual a {1}.
        /// </summary>
        public static string ErrorRangeMin {
            get {
                return ResourceManager.GetString("ErrorRangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser ASCII básico en mayúsculas.
        /// </summary>
        public static string ErrorReAsciiUpercase {
            get {
                return ResourceManager.GetString("ErrorReAsciiUpercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no permitido, campo mandatorio.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser máximo de {1} caracteres.
        /// </summary>
        public static string ErrorStringLength {
            get {
                return ResourceManager.GetString("ErrorStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deber se un número telefónico de 10 dígitos.
        /// </summary>
        public static string ErrorTelephone {
            get {
                return ResourceManager.GetString("ErrorTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser un código postal de 5 dígitos.
        /// </summary>
        public static string ErrorZipCode {
            get {
                return ResourceManager.GetString("ErrorZipCode", resourceCulture);
            }
        }
    }
}
