// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_cat_status_do")]
    public partial class PgCatStatusDo
    {
        public PgCatStatusDo()
        {
            PgFactDistributionOrders = new HashSet<PgFactDistributionOrders>();
        }

        [Key]
        [Column("ID_ST")]
        public int IdSt { get; set; }
        [Required]
        [Column("STATUS")]
        [StringLength(20)]
        [Unicode(false)]
        public string Status { get; set; }

        [InverseProperty("IdStNavigation")]
        public virtual ICollection<PgFactDistributionOrders> PgFactDistributionOrders { get; set; }
    }
}