// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_cat_status_products")]
    public partial class PgCatStatusProducts
    {
        public PgCatStatusProducts()
        {
            PgCatProducts = new HashSet<PgCatProducts>();
        }

        [Key]
        [Column("ID_ST")]
        [StringLength(1)]
        [Unicode(false)]
        public string IdSt { get; set; }
        [Required]
        [Column("STATUS")]
        [StringLength(20)]
        [Unicode(false)]
        public string Status { get; set; }

        [InverseProperty("IdStNavigation")]
        public virtual ICollection<PgCatProducts> PgCatProducts { get; set; }
    }
}