// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_cat_material_category")]
    public partial class PgCatMaterialCategory
    {
        public PgCatMaterialCategory()
        {
            PgCatMaterialType = new HashSet<PgCatMaterialType>();
            PgSelFamily = new HashSet<PgSelFamily>();
            PgSelSalesForce = new HashSet<PgSelSalesForce>();
        }

        [Key]
        [Column("ID_CATEGORY")]
        [StringLength(2)]
        [Unicode(false)]
        public string IdCategory { get; set; }
        [Required]
        [Column("CATEGORY")]
        [StringLength(50)]
        [Unicode(false)]
        public string Category { get; set; }

        [InverseProperty("IdCategoryNavigation")]
        public virtual ICollection<PgCatMaterialType> PgCatMaterialType { get; set; }
        [InverseProperty("IdCategoryNavigation")]
        public virtual ICollection<PgSelFamily> PgSelFamily { get; set; }
        [InverseProperty("IdCategoryNavigation")]
        public virtual ICollection<PgSelSalesForce> PgSelSalesForce { get; set; }
    }
}