// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_cat_status_employee")]
    public partial class PgCatStatusEmployee
    {
        public PgCatStatusEmployee()
        {
            PgCatManagersOthers = new HashSet<PgCatManagersOthers>();
        }

        [Key]
        [Column("ESTEMP")]
        [StringLength(1)]
        [Unicode(false)]
        public string Estemp { get; set; }
        [Column("STATUS")]
        [StringLength(50)]
        [Unicode(false)]
        public string Status { get; set; }

        [InverseProperty("EstempNavigation")]
        public virtual ICollection<PgCatManagersOthers> PgCatManagersOthers { get; set; }
    }
}