// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_cat_material_type")]
    public partial class PgCatMaterialType
    {
        public PgCatMaterialType()
        {
            PgCatProducts = new HashSet<PgCatProducts>();
            PgFactDistributionOrders = new HashSet<PgFactDistributionOrders>();
            PgFactInventories = new HashSet<PgFactInventories>();
        }

        [Key]
        [Column("ID_TYPE")]
        [StringLength(1)]
        [Unicode(false)]
        public string IdType { get; set; }
        [Required]
        [Column("MATERIAL_TYPE")]
        [StringLength(50)]
        [Unicode(false)]
        public string MaterialType { get; set; }
        [Column("EXPIRATION_TIME_MONTH")]
        public int ExpirationTimeMonth { get; set; }
        [Required]
        [Column("ID_CATEGORY")]
        [StringLength(2)]
        [Unicode(false)]
        public string IdCategory { get; set; }

        [ForeignKey("IdCategory")]
        [InverseProperty("PgCatMaterialType")]
        public virtual PgCatMaterialCategory IdCategoryNavigation { get; set; }
        [InverseProperty("IdTypeNavigation")]
        public virtual ICollection<PgCatProducts> PgCatProducts { get; set; }
        [InverseProperty("IdTypeNavigation")]
        public virtual ICollection<PgFactDistributionOrders> PgFactDistributionOrders { get; set; }
        [InverseProperty("IdTypeNavigation")]
        public virtual ICollection<PgFactInventories> PgFactInventories { get; set; }
    }
}