// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_sel_sales_force")]
    public partial class PgSelSalesForce
    {
        [Key]
        [Column("ID_CATEGORY")]
        [StringLength(2)]
        [Unicode(false)]
        public string IdCategory { get; set; }
        [Key]
        [Column("USERNAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string Username { get; set; }
        [Key]
        [Column("SALES_FORCE")]
        [StringLength(10)]
        [Unicode(false)]
        public string SalesForce { get; set; }

        [ForeignKey("IdCategory")]
        [InverseProperty("PgSelSalesForce")]
        public virtual PgCatMaterialCategory IdCategoryNavigation { get; set; }
    }
}