// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GridPromocional.Models
{
    [Table("PG_sel_family")]
    public partial class PgSelFamily
    {
        [Key]
        [Column("ID_CATEGORY")]
        [StringLength(2)]
        [Unicode(false)]
        public string IdCategory { get; set; }
        [Key]
        [Column("ID_FAM")]
        [StringLength(3)]
        [Unicode(false)]
        public string IdFam { get; set; }
        [Column("USERNAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string Username { get; set; }
        [Column("DATE", TypeName = "datetime")]
        public DateTime? Date { get; set; }

        [ForeignKey("IdCategory")]
        [InverseProperty("PgSelFamily")]
        public virtual PgCatMaterialCategory IdCategoryNavigation { get; set; }
        [ForeignKey("IdFam")]
        [InverseProperty("PgSelFamily")]
        public virtual PgCatFamily IdFamNavigation { get; set; }
    }
}